### ISSUE TITLE
Cannot see Stars on Albums

### ISSUE THREAD

**Issue by KillerParticles** [ciderapp/iTheme#19]
On Albums they will typically have little Stars next to the songs that are the most popular, for example, Positions by Ariana Grande has the song Positions as the most popular one in the Album, hence the Star next to it.

However in your theme, the colours are the exact same as the background expect for a slight tink that its almost impossible to see (try finding it in the first image, bet you cant :)
![image](https://user-images.githubusercontent.com/93286201/160623300-f05b3fb9-7b95-48f9-83c3-a66ed6e62b37.png)
![image](https://user-images.githubusercontent.com/93286201/160623344-b23a9c68-c98e-4796-988a-338235484688.png)

**Comment by yazninja** [comment]
Fixed, but if u want apple Icons Back, use Sosumi for now, its in the theme list

**Comment by yazninja** [comment]
@KillerParticles update: plugin now works. Should be able to remember the settings
