### ISSUE TITLE
Controls and Title askew.

### ISSUE THREAD

**Issue by Kings-Cmd** [ciderapp/iTheme#21]
Playback controls too far left and leaks into the left pane.

Apple Music profile picture and Cider title at the top left/top of the left pane are both askew and not centred at the top of the left pane.

![Screenshot 2022-04-22 202355](https://user-images.githubusercontent.com/83033150/164780954-bfb4a561-827c-4596-a22b-6b7f186fc1e4.jpg)

**Comment by yazninja** [comment]
![image](https://user-images.githubusercontent.com/71800112/165952504-6fc1606b-2a6f-409b-9814-e5db9f5690b8.png)
this looks to alrady be fixed, please update your Cider app to have the navbars on the sidebar
