### ISSUE TITLE
Mica/Blur effect is not working on Light Mode.

### ISSUE THREAD

**Issue by KillerParticles** [ciderapp/iTheme#28]
I know you are aware of this, so I thought I'd make a bug report to keep track of it.

What it looked like before:
![image](https://user-images.githubusercontent.com/93286201/166232246-2aafa58e-32e9-445e-96fb-15dc58b82574.png)

What it looks like now:
![image](https://user-images.githubusercontent.com/93286201/166232978-ed9bf714-1660-4a57-8c13-88aa7c6099ef.png)

**Comment by yazninja** [comment]
works now again 1.4.5.2208
