### ISSUE TITLE
Hearts in Playlist/Album view missalligned

### ISSUE THREAD

**Issue by KillerParticles** [ciderapp/iTheme#44]
Ok so techinally from a CSS point of view, this is alligned. However from just looking at it its not alligned.
![image](https://user-images.githubusercontent.com/93286201/173207870-624f4abd-0c6c-4d43-a9c6-3fabe0ff8aaa.png)

**Comment by yazninja** [comment]
![image](https://user-images.githubusercontent.com/71800112/173260210-f313c60f-9544-409f-a5a1-e62788804563.png)
i find it aligned... idk where else to place it

**Comment by yazninja** [comment]
![image](https://user-images.githubusercontent.com/71800112/173260304-cb7d4af8-b0a5-49ee-99c2-dc0cf3d35ec6.png)
if anything, AM web looks more misaligned

**Comment by KillerParticles** [comment]
Yeah, I get why the heart is there, but it's not right.
