### ISSUE TITLE
Mojave layout anomalies when toggling `Hide Library`

### ISSUE THREAD

**Issue by kyrie25** [ciderapp/iTheme#47]
When toggling `Hide Library` while using Mojave layout there are 2 noticeable anomalies:
- Top nav bar is see through where the Library bar once was: 
![image](https://user-images.githubusercontent.com/77577746/177792226-ebf06971-d52c-489e-9b22-9f37c49a2ad6.png)

- Playbar remains at the default position thus leaves a wide space where the library bar once was:
![image](https://user-images.githubusercontent.com/77577746/177792398-76b01ff5-eeeb-4bb6-887a-b77c9b07ea02.png)

**Comment by KillerParticles** [comment]
Is ur Cider up to date? I do not have this problem on newest Cider and iTheme.

**Comment by kyrie25** [comment]
Just manually reinstalled both, can confirm issue has been resolved. Thanks for your time.
