### ISSUE TITLE
Some areas have no blur effect

### ISSUE THREAD

**Issue by SilentVastSky** [ciderapp/iTheme#54]
There is no blur effect in the control bar and lyrics area
It's completely transparent.

![屏幕截图 2022-07-18 223219](https://user-images.githubusercontent.com/65668246/179535359-6a853fa0-fb74-4a4a-b776-a810f258750b.jpg)

Did i set something wrong?

**Comment by KillerParticles** [comment]
can you confirm this is only present on iTheme? can you try base Cider and see if the issue still persists there?

**Comment by SilentVastSky** [comment]
It looks normal after the app update.Thank you for your reply.



发自我的iPhone


------------------ Original ------------------
From: KillerParticles ***@***.***&gt;
Date: Wed,Jul 20,2022 8:31 PM
To: ciderapp/iTheme ***@***.***&gt;
Cc: SilentVastSky ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [ciderapp/iTheme] Some areas have no blur effect (Issue #54)





 
can you confirm this is only present on iTheme? can you try base Cider and see if the issue still persists there?

**Comment by yazninja** [comment]
closing aa issue is resolved
