### ISSUE TITLE
Album view text covered the UI on top of it

### ISSUE THREAD

**Issue by polaraditia** [ciderapp/iTheme#58]
After update **iTheme to last version (3.2.2)**, I found Album view text covered the UI on top of it.
It only happens on Album page view and Recently added page only.
![image](https://user-images.githubusercontent.com/5745134/180916111-2fa127d4-9fca-4e92-9248-5460d1365d55.png)
![image](https://user-images.githubusercontent.com/5745134/180916193-1a642a41-df01-4232-bd3b-ca1f61e516af.png)
![image](https://user-images.githubusercontent.com/5745134/180916277-8b53cd76-eba0-49bf-8c2a-3fdf235b43f3.png)
![image](https://user-images.githubusercontent.com/5745134/180916837-65741b83-68fd-4cec-89e9-b2fbcee30c0e.png)

Album view on Browse page works well.
![image](https://user-images.githubusercontent.com/5745134/180916423-f2739de5-21c1-4902-9c8e-b887cd30281b.png)

Temprorary workaround is disable iTheme
![image](https://user-images.githubusercontent.com/5745134/180916553-7a7c828f-cbdb-4c27-b82e-449114ac85f7.png)

Cider 1.5.1-beta 455 on Windows 11 via winget

**Comment by kyrie25** [comment]
Can't replicate the issue on Cider 1.5.1-beta 470 for me, have you tried running a clean install of Cider/iTheme instead?

![image](https://user-images.githubusercontent.com/77577746/181582144-6b5e8c97-323b-4022-84a7-9fefd33cebd5.png)

**Comment by polaraditia** [comment]
Sorry for late update.
Updating to Cider 1.5.1-beta 470 (last version via winget) and iTheme 3.2.3 fix the issue.
![image](https://user-images.githubusercontent.com/5745134/181664009-1730817a-3cd7-4142-b9a4-9b7f221d99a0.png)
