### ISSUE TITLE
When using this theme, the app's close button displays abnormally.

### ISSUE THREAD

**Issue by GeniusLv2006** [ciderapp/iTheme#59]
The specific situation is shown below (due to network problems, there is a chance that the picture can not be displayed properly)
[![ZQaj6R.png](https://www.helloimg.com/images/2022/08/15/ZQaj6R.png)](https://www.helloimg.com/image/ZQaj6R)

In addition, my screen resolution is 2560 * 1600, the scaling ratio is 200%, the screen ratio is 10:9 (my kind of screen should be relatively rare)
Hope this information is useful to you, thanks.

**Comment by yazninja** [comment]
Hi, this commit should fix that https://github.com/ciderapp/iTheme/commit/cdb23ee8f6081025b152d58c4b8af732bb6be5fc
